FROM quay.io/keycloak/keycloak:26.7.2 AS builder

ENV KC_DB=postgres \
    KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true

USER 1000
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.7.2

COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY --chmod=0555 load-secrets.sh /opt/keycloak/bin/load-secrets.sh

USER 1000
ENTRYPOINT ["/opt/keycloak/bin/load-secrets.sh"]
