apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ekumetrics

commonLabels:
  app.kubernetes.io/part-of: ekumetrics

resources:
  - namespace.yaml
  - postgres.yaml
  - nats.yaml
  - prometheus.yaml
  - loki.yaml
  - tempo.yaml
  - alertmanager.yaml
  - grafana.yaml
  - otel-collector.yaml
  - keycloak.yaml
  - platform-api.yaml
  - ingest-gateway.yaml
  - portal-web.yaml

configMapGenerator:
  - name: nats-config
    files:
      - configs/nats-server.conf
  - name: prometheus-config
    files:
      - configs/prometheus.yml
  - name: prometheus-rules
    files:
      - configs/slo-rules.yml
      - configs/capacity-rules.yml
  - name: loki-config
    files:
      - configs/loki.yaml
  - name: tempo-config
    files:
      - configs/tempo.yaml
  - name: otel-config
    files:
      - configs/otel-config.yaml
  - name: alertmanager-config
    files:
      - configs/alertmanager.yml
  - name: grafana-datasources
    files:
      - configs/grafana-datasources.yml
  - name: grafana-dashboards-provider
    files:
      - configs/grafana-dashboards-provider.yml
  - name: keycloak-realm
    files:
      - configs/ekumetrics-realm.json
  - name: ingest-gateway-config
    files:
      - configs/ingest-gateway.conf.template

generatorOptions:
  disableNameSuffixHash: false
