apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ekumetrics

resources:
  - ../../base
  - ingress.yaml
  - secret-placeholder.yaml

commonLabels:
  environment: lab

patchesStrategicMerge:
  - patches/prometheus-retention.yaml
