export type ChannelType = 'email' | 'slack' | 'webhook';

export type ChannelConfig = {
  to?: string;
  from?: string;
  smarthost?: string;
  username?: string;
  password?: string;
  requireTls?: boolean;
  webhookUrl?: string;
  channel?: string;
  url?: string;
  token?: string;
};

export type RenderableChannel = {
  id: string;
  tenantSlug: string;
  type: ChannelType;
  enabled: boolean;
  severities: string[];
  config: ChannelConfig;
};

const SEVERITIES = ['critical', 'warning', 'info'] as const;

export function yamlQuote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
}

export function receiverName(id: string): string {
  return `eku_${id.replace(/[^a-zA-Z0-9_-]/g, '')}`;
}

export function renderAlertmanagerConfig(
  channels: RenderableChannel[],
): string {
  const active = channels.filter(
    (channel) => channel.enabled && channel.severities.length > 0,
  );
  const routes = active.flatMap((channel) =>
    channel.severities
      .filter((severity) =>
        (SEVERITIES as readonly string[]).includes(severity),
      )
      .map(
        (severity) =>
          `    - matchers:\n        - tenant_id=${yamlQuote(channel.tenantSlug)}\n        - severity=${yamlQuote(severity)}\n      receiver: ${receiverName(channel.id)}\n      continue: true`,
      ),
  );
  const receivers = [
    '  - name: ekumetrics-default',
    ...active.map((channel) => renderReceiver(channel)),
  ];
  return [
    '# Generated by Ekumetrics. Channel secrets live only in this runtime file.',
    'route:',
    '  receiver: ekumetrics-default',
    '  group_by: [alertname, severity, tenant_id, site_id]',
    '  group_wait: 10s',
    '  group_interval: 1m',
    '  repeat_interval: 4h',
    ...(routes.length ? ['  routes:', ...routes] : []),
    'receivers:',
    ...receivers,
    '',
  ].join('\n');
}

function renderReceiver(channel: RenderableChannel): string {
  const name = `  - name: ${receiverName(channel.id)}`;
  const config = channel.config;
  if (channel.type === 'email') {
    const lines = [
      name,
      '    email_configs:',
      '      - to: ' + yamlQuote(config.to ?? ''),
      '        send_resolved: true',
    ];
    if (config.from) lines.push('        from: ' + yamlQuote(config.from));
    if (config.smarthost)
      lines.push('        smarthost: ' + yamlQuote(config.smarthost));
    if (config.username)
      lines.push('        auth_username: ' + yamlQuote(config.username));
    if (config.password)
      lines.push('        auth_password: ' + yamlQuote(config.password));
    if (config.requireTls === false) {
      lines.push('        require_tls: false');
    }
    return lines.join('\n');
  }
  if (channel.type === 'slack') {
    const lines = [
      name,
      '    slack_configs:',
      '      - api_url: ' + yamlQuote(config.webhookUrl ?? ''),
      '        send_resolved: true',
    ];
    if (config.channel)
      lines.push('        channel: ' + yamlQuote(config.channel));
    return lines.join('\n');
  }
  const lines = [
    name,
    '    webhook_configs:',
    '      - url: ' + yamlQuote(config.url ?? ''),
    '        send_resolved: true',
  ];
  if (config.token) {
    lines.push('        http_config:');
    lines.push('          authorization:');
    lines.push('            credentials: ' + yamlQuote(config.token));
  }
  return lines.join('\n');
}
